### ISSUE TITLE
windows环境，三个小问题

### ISSUE THREAD

**Issue by woshiwufei** [HChaoHui/registration_chatgpt#3]
第一是我设置了验证码的apikey，然而每次打开浏览器我点开看拓展程序的输入apikey的位置都是空的，这导致了后续出现图像验证码拓展程序却不能够自动点击
![image](https://github.com/HChaoHui/registration_chatgpt/assets/45104958/75ec2567-e863-4164-aa77-6ec8117c24e7)

第二是在输入姓名那一步（即出现图像验证码前），在我这里大多时候点击continue并没有效果，好像是没有点击到，手动点击后可以继续后续流程。
![image](https://github.com/HChaoHui/registration_chatgpt/assets/45104958/9b095b7c-478e-43bc-b8cc-3a3ffc0a37f9)

第三个是我的问题，headless默认值为‘new’,我改成了‘false’字符串（其实应该是false），导致浏览器没有打开，也就是 #2

**Comment by HChaoHui** [comment]
Hello
第一个问题我目前还不确定是什么bug导致的，可能需要您删掉plugin下cap的目录，然后自己下载一份解压到里面
第二个问题是arkose被bun了导致有个api.js无法加载这个需要后续pandora-next那边修改，或者使用代理
第三个问题flase使用布尔值不使用字符串就好了
您可以先试下我的解决方案，有问题可以再次联系我

**Comment by HChaoHui** [comment]
https://github.com/capsolver/capsolver-browser-extension/releases
这里是下载地址

**Comment by woshiwufei** [comment]
> Hello 第一个问题我目前还不确定是什么bug导致的，可能需要您删掉plugin下cap的目录，然后自己下载一份解压到里面 第二个问题是arkose被bun了导致有个api.js无法加载这个需要后续pandora-next那边修改，或者使用代理 第三个问题flase使用布尔值不使用字符串就好了 您可以先试下我的解决方案，有问题可以再次联系我

通过下载扩展程序自己替换的方式可以解决第一个问题，第二个就等pandora-next作者修吧，最后谢谢解答🫡
